[general]
debug = true
app_name = "Disco Express"

classics_file = "data/classics.csv"
charts_file = "data/charts.csv"
current_charts = "data/current_charts.csv"
slurs_file = "data/slurs.txt"

log_directory = "logs" # relative to apps execution directory

auto_close_time = 600  # in seconds
server_refresh_interval = 10  # in seconds
wish_sending_time = 10 # in seconds
banner_speed = 100 # in millisekunden: interval in welchem das banner um einen Buschstaben weiter rückt

######### DOCUMENTS

documents_directory = "documents"

######### ICONS

[icons]
artist_icon = "icons/artist.svg"
song_icon = "icons/song.svg"
file_icon = "icons/file.svg"
error_icon = "icons/error.svg"
home_icon = "icons/home.svg"
charts_plays_icon = "icons/chart.svg"
unavailable_icon = "icons/unavailable.svg"

######### NETWORK

[network]
server_ip = "localhost"
server_port = 8080

######### COLORS
[style]
background_image = "img/jukebox_comic.jpg"
background_darkness_factor = 0.7
# je stärker der glow (neon) desto schlechter ist die performance
ui_glow_strength = 128
text_glow_strength = 128

[style.colors]
background_color = "#f5ebe0"
text_color = "#5DCAE6"

accent1_glow = "#80ffdb"
accent1 = "#48bfe3"
accent1_dark = "#4895ef"

highlight_glow = "#ff0a54"
highlight = "#ff7096"
off_highlight = "#e01e37"

icon_color = "#f5ebe0"

white = "#f5ebe0"
red = "#e01e37"

disabled_light = "#ced4da"
disabled = "#adb5bd"
disabled_dark = "#6c757d"

######### LANGUAGES

[[languages]]
language_name = "german"
language_icon = "icons/de.svg"

heading_music_wish = "Geben Sie einen Musikwunsch an. Sie können diesen Musikwunsch auch an eine Person richten!"
heading_home = "Willkommen beim Disco Express. Hier können Sie sich ein Lied wünschen oder Informationen zum Fahrgeschäft erhalten."
heading_information = "Wählen Sie eines der Dokumente um mehr zu erfahren."

home_info_btn = "Information"
home_music_wish_btn = "Musik Wunsch"

music_title = "Musik Titel"
music_interpret = "Interpret"
music_sender = "Von"
music_receiver = "Für"
music_message = "Nachricht"

btn_quick_selection = "Schnelle Auswahl"
btn_send = "Anfrage Senden"

error_no_title = "Kein Titel angegeben!"
error_no_interpret = "Kein Interpret angegeben!"
error_slur_found = "{} enthält eine Beleidigung!"
error_dj_unavailable = "Der DJ nimmt momentan keine neuen Musikwünsche an. Bitte versuche es später erneut."
error_network = "Anfrage konnte nicht gesendet werden! Bitte wende dich an einen Admin"
error_no_connection_to_server = "Server unerreichbar! Bitte kontaktieren Sie einen Administrator"

classics_artist_description = "Interpret"
classics_song_description = "Musik Titel"

loading_description = ["Suche CD heraus ...", "Lege CD ein ...", "Packe deinen Song in die Warteschlange ..."]
loading_success = "Musikwunsch erfolgreich versendet!"


[[languages]]
language_name = "english"
language_icon = "icons/gb.svg"
app_name = "Disco Express"

heading_music_wish = "Enter a music wish. You can also direct this wish to someone!"
heading_home = "Welcome to the Disco Express, make a music wish or retrieve some infotmation about us!"
heading_information = "Choose a document to learn more."

home_info_btn = "Information"
home_music_wish_btn = "Music Wish"

music_title = "Music Title"
music_interpret = "Artist"
music_sender = "From"
music_receiver = "For"
music_message = "Message"

btn_quick_selection = "Quick Selection"
btn_send = "Send Request"

error_no_title = "No Title entered!"
error_no_interpret = "No Interpret entered!"
error_slur_found = "{} contains a slur!"
error_dj_unavailable = "The DJ does currently not accept wishes. Please try later again."
error_network = "Request could not be sent! Please refer to an Admin"
error_no_connection_to_server = "Server unavailable! Please contact an Admin"

classics_artist_description = "Artist"
classics_song_description = "Music Title"

loading_description = ["Finding Disc ...", "Inserting Disc ...", "Putting song in queue ..."]
loading_success = "Your music wish was sent sucessfully!"